# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: blabber
run-name: Push Validation (executed by @${{ github.actor }} on ${{ github.event.repository.updated_at }})

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Build users-api
      run: |
        cd users-api
        go build -v
    - name: Test users-api
      run: |
        cd users-api
        go test -v ./...
    - name: Benchmark users-api
      run: |
        cd users-api
        go test -v -run=NONE -bench=. ./...
    - name: Run Fuzz Tests for users-api
      run: |
        cd users-api
        go test -v -run=NONE -fuzz=FuzzGenerateHash -fuzztime=1m ./utils